-- Table: public.Employees

-- DROP TABLE IF EXISTS public."Employees";

CREATE TABLE IF NOT EXISTS public."Employees"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "FirstName" text COLLATE pg_catalog."default" NOT NULL,
    "LastName" text COLLATE pg_catalog."default" NOT NULL,
    "PreferredName" text COLLATE pg_catalog."default" NOT NULL,
    "Email" text COLLATE pg_catalog."default" NOT NULL,
    "Phone" text COLLATE pg_catalog."default" NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "OfficeId" integer NOT NULL,
    "DepartmentId" integer NOT NULL,
    "JobTitleId" integer NOT NULL,
    "Salary" numeric NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "CreatedBy" text COLLATE pg_catalog."default" NOT NULL,
    "ModifiedOn" timestamp with time zone NOT NULL,
    "ModifiedBy" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Employees" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Employees_Departments_DepartmentId" FOREIGN KEY ("DepartmentId")
        REFERENCES public."Departments" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_Employees_JobTitles_JobTitleId" FOREIGN KEY ("JobTitleId")
        REFERENCES public."JobTitles" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_Employees_Offices_OfficeId" FOREIGN KEY ("OfficeId")
        REFERENCES public."Offices" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Employees"
    OWNER to postgres;
-- Index: IX_Employees_DepartmentId

-- DROP INDEX IF EXISTS public."IX_Employees_DepartmentId";

CREATE INDEX IF NOT EXISTS "IX_Employees_DepartmentId"
    ON public."Employees" USING btree
    ("DepartmentId" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_Employees_JobTitleId

-- DROP INDEX IF EXISTS public."IX_Employees_JobTitleId";

CREATE INDEX IF NOT EXISTS "IX_Employees_JobTitleId"
    ON public."Employees" USING btree
    ("JobTitleId" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_Employees_OfficeId

-- DROP INDEX IF EXISTS public."IX_Employees_OfficeId";

CREATE INDEX IF NOT EXISTS "IX_Employees_OfficeId"
    ON public."Employees" USING btree
    ("OfficeId" ASC NULLS LAST)
    TABLESPACE pg_default;